version: '1'
services:
  postgres:
    image: timescale/timescaledb:1.7.4-pg11
    restart: unless-stopped
    environment:
      POSTGRES_DB: health-monitoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5432
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
